import argparse
import pathlib
import re

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches

# Paths (project root is two levels up from this script when run)
PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
README_PATH = PROJECT_ROOT / "README.md"
INFRA_PATH = PROJECT_ROOT / "Wave3-Operations-Infrastructure-Design.md"
DOC_OUTPUT_NAME = "Recoup_Technical_Documentation.docx"
# Image generated by generate_image tool will be placed in the artifacts directory
ARTIFACTS_DIR = pathlib.Path("C:/Users/haris/.gemini/antigravity/brain/0bd0b9d8-0f57-4110-9f5d-a093dcdc4608")
ARCH_IMG = ARTIFACTS_DIR / "architecture_diagram.png"

def extract_section(text, heading):
    """Return markdown text for a given heading (e.g., "## Architecture")."""
    pattern = rf"(^##\s+{re.escape(heading)}\b.*?)(?=^##\s|\Z)"
    match = re.search(pattern, text, flags=re.MULTILINE | re.DOTALL)
    return match.group(1).strip() if match else ""

def clean_mermaid_block(md_section):
    """Extract mermaid code from a markdown code fence.
    Returns the code without the surrounding fences.
    """
    m = re.search(r"```mermaid\n(.*?)\n```", md_section, flags=re.DOTALL)
    return m.group(1).strip() if m else ""

def add_heading(doc, text, level=1):
    doc.add_heading(text, level=level)

def add_paragraph(doc, text):
    p = doc.add_paragraph()
    p.add_run(text)

def main():
    parser = argparse.ArgumentParser(description="Generate Recoup technical documentation as a Word file.")
    parser.add_argument("--output", help="Output docx filename", default=DOC_OUTPUT_NAME)
    args = parser.parse_args()

    # Load source markdown files
    readme_md = README_PATH.read_text(encoding="utf-8")
    infra_md = INFRA_PATH.read_text(encoding="utf-8")

    # Curated sections
    overview = extract_section(readme_md, "The Problem")
    what_it_does = extract_section(readme_md, "What This Agent Actually Does")
    architecture_md = extract_section(readme_md, "Architecture")
    tech_stack = extract_section(readme_md, "Tech Stack")
    project_structure = extract_section(readme_md, "Project Structure")
    env_vars = extract_section(readme_md, "Environment Variables")
    api_surface = extract_section(readme_md, "API Surface")
    security = extract_section(infra_md, "Security Considerations")
    scaling = extract_section(infra_md, "Scaling Considerations")

    doc = Document()

    # Cover page
    cover = doc.add_section()
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Recoup")
    run.bold = True
    run.font.size = docx.shared.Pt(48)
    doc.add_page_break()

    # Title page
    add_heading(doc, "Recoup Technical Documentation", level=1)
    doc.add_paragraph("Generated on: " + pathlib.Path.now().strftime("%Y-%m-%d"))
    doc.add_page_break()

    # Table of Contents placeholder – Word can generate TOC from heading styles
    add_heading(doc, "Table of Contents", level=1)
    doc.add_paragraph("(Use Word's References → Table of Contents to insert automatically)")
    doc.add_page_break()

    # Sections
    add_heading(doc, "Overview", level=1)
    add_paragraph(doc, overview)

    add_heading(doc, "What the Agent Does", level=1)
    add_paragraph(doc, what_it_does)

    add_heading(doc, "Architecture Diagram", level=1)
    if ARCH_IMG.exists():
        doc.add_picture(str(ARCH_IMG), width=Inches(6))
    else:
        doc.add_paragraph("[Architecture diagram missing]")
    add_paragraph(doc, "Figure: High‑level data flow of Recoup.")
    doc.add_page_break()

    add_heading(doc, "Architecture Details", level=1)
    add_paragraph(doc, architecture_md)

    add_heading(doc, "Tech Stack", level=1)
    add_paragraph(doc, tech_stack)

    add_heading(doc, "Project Structure", level=1)
    add_paragraph(doc, project_structure)

    add_heading(doc, "Environment Variables", level=1)
    add_paragraph(doc, env_vars)

    add_heading(doc, "API Surface", level=1)
    add_paragraph(doc, api_surface)

    add_heading(doc, "Security Model", level=1)
    add_paragraph(doc, security)

    add_heading(doc, "Scaling Considerations", level=1)
    add_paragraph(doc, scaling)

    # Save
    output_path = PROJECT_ROOT / args.output
    doc.save(str(output_path))
    print(f"Documentation written to {output_path}")

if __name__ == "__main__":
    main()
